import { useState } from 'react';
import { useDropzone } from 'react-dropzone';
import { useMutation } from '@tanstack/react-query';
import {
  HiOutlineCheckCircle,
  HiOutlineCloudUpload,
  HiOutlineDocument,
  HiOutlineExclamationCircle,
  HiOutlineInformationCircle,
} from 'react-icons/hi';
import { vcfApi } from '../api/client';
import type { Plex34StructureOutputResponse } from '../types';
import { Plex34AncestryMap } from './Plex34AncestryMap';
import { getSupportedProbabilities, getTopSupportedRegion } from './plex34AncestryRegions';

export const Plex34StructureOutputCard = () => {
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [parsedOutput, setParsedOutput] = useState<Plex34StructureOutputResponse | null>(null);
  const [showAdditionalSamples, setShowAdditionalSamples] = useState(false);

  const parseMutation = useMutation({
    mutationFn: vcfApi.parsePlex34StructureOutput,
    onSuccess: (data) => {
      setParsedOutput(data);
    },
    onError: (error) => {
      console.error('PLEX-34 STRUCTURE output parse error:', error);
    },
  });

  const handleDrop = (acceptedFiles: File[]) => {
    const selectedOutputFile = acceptedFiles[0];
    if (selectedOutputFile) {
      setSelectedFile(selectedOutputFile);
      setParsedOutput(null);
      setShowAdditionalSamples(false);
      parseMutation.reset();
    }
  };

  const { getRootProps, getInputProps, isDragActive } = useDropzone({
    onDrop: handleDrop,
    accept: {
      'text/plain': ['.txt', '.out'],
      'application/octet-stream': ['.out'],
    },
    multiple: false,
  });

  const handleParse = () => {
    if (!selectedFile) {
      return;
    }

    parseMutation.mutate(selectedFile);
  };

  const primaryAncestryRow = parsedOutput?.ancestry_rows[0] ?? null;

  return (
    <div className="analysis-shell min-w-0 animate-slide-up">
      <div className="analysis-core space-y-4 p-4 sm:p-5">
        <div className="flex flex-col gap-3 sm:flex-row sm:items-start">
          <div className="rounded-xl border border-[color-mix(in_srgb,var(--color-primary)_32%,var(--color-border))] bg-[color-mix(in_srgb,var(--color-primary)_10%,var(--color-card))] p-2.5 text-[var(--color-primary)]">
            <HiOutlineCloudUpload className="h-6 w-6" />
          </div>
          <div className="space-y-1">
            <h3 className="text-lg font-black leading-tight tracking-[-0.035em] text-[var(--color-text)] sm:text-xl">Output STRUCTURE</h3>
            <p className="text-sm leading-6 text-[var(--color-text-muted)]">Upload the .txt or .out file generated by external STRUCTURE.</p>
          </div>
        </div>

        <div className="rounded-2xl border border-[color-mix(in_srgb,var(--color-info)_30%,var(--color-border))] bg-[color-mix(in_srgb,var(--color-info)_10%,var(--color-card))] p-3">
          <p className="flex items-start gap-2 text-sm leading-6 text-[var(--color-text-muted)]">
            <HiOutlineInformationCircle className="mt-0.5 h-5 w-5 flex-shrink-0 text-[var(--color-info)]" />
            <span>The app reads the uploaded STRUCTURE output, highlights the highest supported cluster, and preserves extracted lines for audit. STRUCTURE execution remains outside this system.</span>
          </p>
        </div>

        <div {...getRootProps()} className={`dropzone-surface glass-hover relative cursor-pointer rounded-2xl border-2 border-dashed p-5 ${isDragActive ? 'dropzone-surface--active-brand' : 'dropzone-surface--brand'}`}>
          <input {...getInputProps()} />
          <div className="flex flex-col items-center justify-center gap-3 text-center">
            <HiOutlineCloudUpload className="h-10 w-10 text-[var(--color-primary)]" />
            <div className="space-y-1">
              <p className="font-bold text-[var(--color-text)]">{isDragActive ? 'Drop the output here' : 'Drag the STRUCTURE output here'}</p>
              <p className="text-sm text-[var(--color-text-muted)]">or click to select a .txt or .out file</p>
            </div>
            <div className="flex items-center gap-2 text-xs text-[var(--color-text-muted)]">
              <span className="rounded-full border border-[var(--color-border)] bg-[var(--color-card)] px-3 py-1 font-mono">TXT</span>
              <span className="rounded-full border border-[var(--color-border)] bg-[var(--color-card)] px-3 py-1 font-mono">OUT</span>
            </div>
          </div>
        </div>

        {selectedFile ? (
          <div className="data-surface rounded-2xl p-4">
            <div className="flex min-w-0 items-center gap-3">
              <HiOutlineDocument className="h-7 w-7 flex-shrink-0 text-[var(--color-primary)]" />
              <div className="min-w-0">
                <p className="truncate font-bold text-[var(--color-text)]">{selectedFile.name}</p>
                <p className="text-xs text-[var(--color-text-muted)]">{(selectedFile.size / 1024).toFixed(2)} KB</p>
              </div>
            </div>
          </div>
        ) : null}

        <button onClick={handleParse} disabled={!selectedFile || parseMutation.isPending} className="btn-primary w-full px-4 text-base">
          {parseMutation.isPending ? (
            <span className="flex items-center justify-center gap-3">
              <span className="h-5 w-5 rounded-full border-2 border-white/45 border-t-white motion-safe:animate-spin" />
              Processing output...
            </span>
          ) : (
            <span className="flex items-center justify-center gap-3">
              <HiOutlineCloudUpload className="h-6 w-6" />
              Process STRUCTURE output
            </span>
          )}
        </button>

        {parseMutation.error ? (
          <div className="rounded-2xl border border-[color-mix(in_srgb,var(--color-error)_42%,var(--color-border))] bg-[color-mix(in_srgb,var(--color-error)_10%,var(--color-card))] p-5 animate-slide-up">
            <div className="flex items-start gap-3">
              <HiOutlineExclamationCircle className="mt-0.5 h-6 w-6 flex-shrink-0 text-[var(--color-error)]" />
              <div className="space-y-1">
                <p className="text-lg font-bold text-[var(--color-text)]">Unable to parse the output.</p>
                <p className="text-sm text-[var(--color-text-muted)]">{parseMutation.error.message}</p>
              </div>
            </div>
          </div>
        ) : null}

        {parsedOutput ? (
          <div className="space-y-4 animate-slide-up">
            <div className="rounded-2xl border border-[color-mix(in_srgb,var(--color-primary)_42%,var(--color-border))] bg-[color-mix(in_srgb,var(--color-primary)_10%,var(--color-card))] p-4">
              <div className="flex items-start gap-3">
                <HiOutlineCheckCircle className="mt-0.5 h-6 w-6 flex-shrink-0 text-[var(--color-primary)]" />
                <div className="space-y-1">
                  <p className="font-bold text-[var(--color-text)]">STRUCTURE output processed successfully</p>
                  <p className="text-sm text-[var(--color-text-muted)]">{parsedOutput.message} ({parsedOutput.count} sample lines)</p>
                </div>
              </div>
            </div>

            {primaryAncestryRow ? (
              <Plex34AncestryMap row={primaryAncestryRow} />
            ) : (
              <div className="rounded-2xl border border-[color-mix(in_srgb,var(--color-info)_30%,var(--color-border))] bg-[color-mix(in_srgb,var(--color-info)_10%,var(--color-card))] p-4">
                <p className="flex items-start gap-2 text-sm leading-6 text-[var(--color-text-muted)]">
                  <HiOutlineInformationCircle className="mt-0.5 h-5 w-5 flex-shrink-0 text-[var(--color-info)]" />
                  <span>No structured ancestry row was detected; use the raw table below as extracted detail.</span>
                </p>
              </div>
            )}

            {parsedOutput.ancestry_rows.length > 1 ? (
              <div className="space-y-3">
                <label className="flex cursor-pointer items-center gap-2 group">
                  <input type="checkbox" checked={showAdditionalSamples} onChange={(event) => setShowAdditionalSamples(event.target.checked)} className="h-4 w-4" />
                  <span className="text-sm text-[var(--color-info)] transition-colors group-hover:brightness-110">Show additional STRUCTURE samples ({parsedOutput.ancestry_rows.length - 1})</span>
                </label>

                {showAdditionalSamples ? (
                  <div className="grid gap-3 sm:grid-cols-2">
                    {parsedOutput.ancestry_rows.slice(1).map((row) => {
                      const topRegion = getTopSupportedRegion(getSupportedProbabilities(row));

                      return (
                        <div key={row.row_index} className="data-surface rounded-2xl p-3">
                          <div className="flex items-center justify-between gap-3">
                            <div className="min-w-0">
                              <p className="text-xs font-bold uppercase tracking-[0.18em] text-[var(--color-primary)]">Additional sample</p>
                              <p className="truncate font-bold text-[var(--color-text)]">{row.sample_id}</p>
                            </div>
                            <span className="font-mono text-sm font-bold text-[var(--color-secondary)]">{(topRegion.probability * 100).toFixed(1)}%</span>
                          </div>
                          <p className="mt-2 text-sm font-semibold text-[var(--color-text-muted)]">{topRegion.label}</p>
                        </div>
                      );
                    })}
                  </div>
                ) : null}
              </div>
            ) : null}

            <div className="data-surface overflow-hidden rounded-2xl">
              <div className="border-b border-[var(--color-border)] bg-[color-mix(in_srgb,var(--color-primary)_9%,var(--color-card))] px-4 py-3">
                <p className="text-sm font-bold text-[var(--color-text)]">Extracted raw lines</p>
              </div>
              <div className="max-h-64 overflow-auto">
                <table className="min-w-full text-xs">
                  <thead className="sticky top-0 border-b border-[var(--color-border)] bg-[var(--color-card-strong)]">
                    <tr>
                      <th className="px-4 py-3 text-left font-bold text-[var(--color-primary)]">#</th>
                      <th className="px-4 py-3 text-left font-bold text-[var(--color-info)]">Extracted line</th>
                    </tr>
                  </thead>
                  <tbody>
                    {parsedOutput.sample_lines.map((line, index) => (
                      <tr key={`${index}-${line}`} className="border-t border-[var(--color-border)] transition-colors hover:bg-[color-mix(in_srgb,var(--color-primary)_7%,var(--color-card))]">
                        <td className="px-4 py-2 font-mono text-[var(--color-text-muted)]">{index + 1}</td>
                        <td className="whitespace-pre px-4 py-2 font-mono text-[var(--color-text)]">{line}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        ) : null}
      </div>
    </div>
  );
};
