import { HirisplexSResultsUploadCard } from './HirisplexSResultsUploadCard';
import { Plex34StructureOutputCard } from './Plex34StructureOutputCard';

export const ResultsUploadSection = () => {
  return (
    <div className="space-y-5">
      <div className="rounded-2xl border border-[color-mix(in_srgb,var(--color-info)_30%,var(--color-border))] bg-[color-mix(in_srgb,var(--color-info)_10%,var(--color-card))] p-4">
        <p className="text-sm leading-6 text-[var(--color-text-muted)]">
          These readers accept result files already generated by external tools. They do not depend on the VCF upload or validation on this page.
        </p>
      </div>
      <div className="mx-auto grid w-full max-w-[min(100%,104rem)] min-w-0 items-start gap-5 xl:grid-cols-2">
        <HirisplexSResultsUploadCard />
        <Plex34StructureOutputCard />
      </div>
    </div>
  );
};
